### PR TITLE
Mapfixes Pass (Part 1)

### LINKED ISSUE #656: the surface mining room's airlock is all access
#### Brief description of the issue
the surface mining room's airlock is all access
the mining gear has strangely special lockers with no lock but with mining gear in it including KA's

it allowed a baldie to powergame and steal one as an intern and parade around in full mining gear

#### What you expected to happen
for the mining airlock to have mining access restrictions

#### What actually happened
the baldie was equipped with a KA by just walking in like a good powergamer

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Don't mind the actual commit name, not sure what happened there.

This PR goes through and tackles some odds and ends, such as;
- Fixes #656 (surface mining access): the exterior is all-access so that it can be used for shelter in the event of a storm, but the interior and controller require mining area access.
- Similarly, the Security Outpost mentioned in that PR is set up in the same way now, and access into Security itself, above the Armory, also works the same way. The button outside at Security proper should now actually work (using wrong subtype).
- Yes, I have hand-tested all of these access changes and verified they work.
- Updated Engineering's access locks to function the same way, so they can't be used to sneak in.

Misc changes:
1) Rejiggered some cables out by the Commerce Pad, will keep it from throwing power alarms. Commerce Pad mapping area now has a distinctive area icon too.
2) Cleaned up some dead-end piping in Gateway Arrivals. Looks like it used to (or was going to) run out to Exploration but doesn't any more.
3) Fixed a missing window in one of the Security cells.
4) Added some (closed) shutters to the empty Security Office.
5) Removed some pointless duplicated windows from around Sec.
6) Added a table next to the Armory lathe so that you don't have to throw the metal/glass on the floor or next to the chargers.

Cleared up some inventory gaffes with voidsuits, mostly in Engineering. Changes as follows;
1) Engineering suit bay was a hot mess; duplicate magboots and helmets galore. Surplus items have been cleaned up and shipped back to Central.
2) Two Engineering voidsuits were replaced with a Construction voidsuit and a HAZMAT voidsuit. Construction suit is cosmetic, but the HAZMAT suit actually has 100% rad protection.
3) The Medical voidsuit in the EMT bay was replaced with an EMT voidsuit.
4) Two Medical voidsuits have been issued to the Field Medics in Exploration. This necessitated redoing the Prep Room a little.
5) One of the two Pilot voidsuits starts out as the blue subtype, 'cause why not?
6) A "backup" Atmospherics voidsuit and cycler have been installed down in Atmospherics.

### CODE REVIEW

**Comment by Repede** [comment]
That makes me think, Field Medics couldn't enter the prep room for a while. Dunno if it was logged though.

**Comment by SplinterGP** [comment]
> That makes me think, Field Medics couldn't enter the prep room for a while. Dunno if it was logged though.

it is caused by the room needing explorer access but the Field Medics don't have it

**Comment by KillianKirilenko** [comment]
Looking into this now. I can either add a new access level *or* add the medical_equip access level to it (which will let pretty much the **entire medical department** wander in more or less unmolested. Opinions?

**Comment by SplinterGP** [comment]
sounds fine to add the medical_equip access to it, once they'll not be able to get other stuff anyway

**Comment by SplinterGP** [comment]
but making a new access level sounds more reasonable, unless it has some limit

**Comment by KillianKirilenko** [comment]
New access levels are trivial and only really limited by the possibility of clashes if upstreams add more access levels.

The main reason I think a new access level is a good idea is that access_medical_equip is on the SAR lockers as well; if you've got that, MD McBaldersson or any other medical staffer can wander in and grab themselves all the regular SAR gear from that room.

**Comment by Repede** [comment]
Or have a different room for Field Medics for their equip maybe?

**Comment by KillianKirilenko** [comment]
Wouldn't help. Again, the issue is that every member of Medical has `access_medical_equip`. If FMs use that to get into Exploration and get their gear, then so can any member of Medical.

As for `access_explorer`; I assume because that would let them open explorer equipment lockers and fly the shuttle.

**Comment by Repede** [comment]
The pilot doesn't have their own access I assume, weh.. Though I don't mind regular medics having access to SAR's stuff since SAR has access to almost all of medbay save surgery and chemistry. And there isn't much for a medic to steal except a knife and a gun that does nothing on the outpost..

I wonder how they do it on Polaris/Tether then.

**Comment by KillianKirilenko** [comment]
Pilot does in fact have its own access level. The odd one out is the *Pathfinder*. (Fun fact; on Tether, the RD & HoS have, or at least had, access to the PF's office!)

Basically the entire Exploration department is a little bit of a mess in... eh, almost every regard, really.

**Comment by SplinterGP** [comment]
the HOS and RD has access to PF office ye

**Pull request merged**
