### PR TITLE
[FIX] Update/Fix Vulp Mask.dmi

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Renames several sprites in the vulp-specific mask.dmi in order to fix cigarettes, cigars, and similar smokable items not appearing when equipped to the mask slot. Also ports a halfmask sprite from CitRP.

### CODE REVIEW

**Comment by Repede** [comment]
Should this be possibly ported upstream since that means their vulps have the same problem right?

**Comment by TheFurryFeline** [comment]
It's an upstream issue, yes. Needs to be ported to Virgo, or even Polaris.

**Comment by KillianKirilenko** [comment]
I doubt Polaris does, they're a Paradise invention that was ported to Virgo from what I know. The issue stems from the fact Paradise uses a slightly different bay branch where the smokable sprites use different names, and when they were ported to Virgo the names weren't fixed.

**Comment by izac112** [comment]
#620 Travis had a hissy fit so just doing it this way

**Pull request closed without merging**
