### PR TITLE
Rad-X change / Re-Adds vent sounds

### PR DESCRIPTION
**Pull request by izac112**
- Rad-X Overdose is now 45 so you cant just fill yourself with infinit amounts
- Rad-X now metabs because its not nanites that avoids your bodily functions until it detects radiation.
- Re-Adds Vent sounds because the reported issues that vore had with them have never been reported here and polaris has it active plus, if you don't like them you can just turn them off.

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
You figured out the vent sound issues so they don't stack up with each other? @Rykka-Stormheart knows about this stuff, btw, since it's their addition upstream which was commented out because of some issues in the first place.

**Comment by izac112** [comment]
The issues have never been reported here and they are active on polaris git, so far as i am aware nothing is broken.

**Comment by izac112** [comment]
Though preventing stacking would be nice its not worth commenting out all the sounds and completely killing it, unless a fix for the stacking is already on the horizon

**Comment by TheFurryFeline** [comment]
https://github.com/VOREStation/VOREStation/issues/6234 is part of the reported issues with the vent sounds, to note.

**Comment by izac112** [comment]
Yeah, i know i looked at it before i made this pr, never had any reports or experienced this.

**Comment by TheFurryFeline** [comment]
I just thought I'd bring it up because I remember them being disabled for stacking reasons. Sound code is black magic to me, though, so I dunno how to fix it. <W<

**Comment by izac112** [comment]
There be nice if there was  a way to set don't have more then (insertnumber) of loops using the same sound, but sadly not as far as i am aware.

**Pull request merged**
