### PR TITLE
Adds an upgrade for translators that allows them to understand every language

### LINKED ISSUE #470: Translators don't work on several languages
#### Brief description of the issue
Unless that's actually meant ICly, the handheld translator, the earpiece, or the circuitry-hand-made translators won't translate certain languages (such as Vox, for instance, among several others).

#### What you expected to happen
To understand what the other was saying in it's native tongue.

#### What actually happened
I did not understand what the other was saying in it's native tongue.

#### Steps to reproduce
1-Have aliens talk to you in alien languages while you're using translating gear.
2-You didn't understand what they said.

#### Code Revision
- (Found using the "Show Server Revision" verb under the OOC tab.)
 
#### Anything else you may wish to add:
- (Location if it's a mapping issue, screenshots, sprites, etc.)

### PR DESCRIPTION
**Pull request by cebutris**
I mean, they're supposed to be universal. At least we can make them universal. 

The upgrade requires 6 Data theory and 6 Biological, though these can change.

Closes #470

### CODE REVIEW

**Comment by izac112** [comment]
Like hawk said "Translators are coded to deal with specifics only and not know others. It won't do Rootspeak either. This could be changed, but by code, it's working as intended last I knew."

Though i don't see a reason why it should be changed as for the root speak example the language is not based on vision or sound

**Comment by cebutris** [comment]
If this doesn't need to change, then the issue should be closed. I made this to close the issue

**Comment by izac112** [comment]
Personally did not know it was an open issue, if i knew i would have closed it but now that i know about i can.

**Comment by cebutris** [comment]
issue closed, I consider this a win

**Pull request closed without merging**
