### PR TITLE
adds shovel and ice pick to autolathe #591

### PR DESCRIPTION
**Pull request by Hawk-v3**

### CODE REVIEW

**Comment by Hawk-v3** [comment]
@cebutris code/datums/autolathe/tools_yw.dm:3:error: /obj/item/weapon/ice_pick: undefined type path

**Comment by SplinterGP** [comment]
My guess its because where the item is, it's on the YW Map stuff, might be wrong

**Comment by Hawk-v3** [comment]
I am 95% sure you're right, because the map files don't start autochecked, so it's fucking it over on an earlier test.

**Comment by SplinterGP** [comment]
can be that, yeah, should probably move it to somewhere else that ain't map files

**Pull request merged**
