### PR TITLE
Adds jungle VR map

### PR DESCRIPTION
**Pull request by Repede**
A little pvp thing with some animals inbetween. Plus puts the vr stuff on a new Z layer which is lateloaded

### CODE REVIEW

**Comment by Repede** [comment]
Just need to test every VR Map to make sure they are still loading properly and the lighting/stuff is fine. Otherwise good to go.

**Comment by izac112** [comment]
Please move and rename /maps/yw_vrstuff to /maps/yw/vrstuff

**Comment by Repede** [comment]
Will move the vrworld area, but I put this stuff outside the /yw/ map folder in case we ever use a different map one day since this is a standalone z level that could be used anywhere (like redgate being its own folder). But if we want to keep everything we do in the yw folder that's fine too.

**Comment by izac112** [comment]
If we got a new map we have to redo some of our folder structure anyways including residentials, It be easier for now if we keep yw map shit contained to the yw folder as there is a bigger chance upstream does a change to their structure then it is for us to get a completely new map anytime soon. 

Plus it makes it easier to do mass changes across YW only stuff if its all contained in the same map folder.

**Comment by Repede** [comment]
added to yw folder

**Pull request merged**
