### PR TITLE
Command Secretary Access Changes

### PR DESCRIPTION
**Pull request by cebutris**
This PR gives the Command Secretary the Request Console Announcement access. This allows them to help facilitate communication between the command staff and the crew when the command staff are too busy being command staff to head to a console for an annnouncement

### CODE REVIEW

**Comment by RadiantFlash7** [comment]
Hm. I like the idea of giving them rc access,
I am however, hesitant on medical and security.
Given the command secretary is for command staff, I’m not actually sure when you’d need the medical records access, for the cmo. Any updates to their records are likely done on the spot, given huds or in a specific room in their department.

**Comment by izac112** [comment]
The rc announcement looks fine to me, but the reason they don't have more access then they do is because they are civilians and should there for not have access to confidential medical or security records.
They should absolutely not be able to make warrants.

**Comment by Repede** [comment]
I'm with Izac on that, Secretary is a secretary and some information are indeed confidential and should remain that way.

**Comment by cebutris** [comment]
Med/sec access removed, it's just the RC announcement now

**Comment by cebutris** [comment]
Why do you hurt me, Travis? Why do you do the things that you do?

**Pull request merged**
