### PR TITLE
Adds sec and engineering Zaddat suits into Xenowear(They have Extra armor values) 

### PR DESCRIPTION
**Pull request by SplinterGP**
Hope travis aint dumh man this time

### CODE REVIEW

**Comment by izac112** [comment]
Travis dum ye https://github.com/Yawn-Wider/YWPolarisVore/pull/729

**Comment by izac112** [comment]
still the same problem not running on the latest commit but running fine on every one before.

**Comment by SplinterGP** [comment]
Seems like travis likef being on thqt build forever, gah

**Comment by izac112** [comment]
What about a commit try making one with a comment or something

**Comment by SplinterGP** [comment]
It worked yat

**Pull request merged**
