### PR TITLE
More tools for Pupdozer and Research Hound modules to bring them more in line with existing borg modules

### PR DESCRIPTION
**Pull request by Holdelta**
Adding features from the other borg modules over to the dogborg versions.

Pupdozer:
- Air Analyzer
- Pipe Painter
- Floor Painter
- Geiger Counter
- Plasteel manipulator

Research Hound:
- ID card to open other borg interfaces
- Organ gripper
- Mech part gripper
- Robot Analyzer
- Welding tool
- Wrench
- Wirecutters
- Multitool
- Nanopaste reserves
- Wire reserves

### CODE REVIEW

**Comment by Hawk-v3** [comment]
That research borg is way too powerful. IF that's what the base research borg has, they're both too powerful.

**Comment by Holdelta** [comment]
So, that's the interesting thing, the current research robot has more than this, as it has the ability to operate(assuming this is used to operate on synthetic crew as they have scalpels and circular saws as well), jumpers to revive synthetic crew and xeno tools to perform xenobiology.

I just added "enough" features so that they can build mechs, which I'm assuming is too much?  These tools are already pre-existing on the normal research module, so mind telling me a few things I can remove from the Research Hound to see approval?

**Comment by Hawk-v3** [comment]
If they're on the Research Borg, that's honestly fine, in line is not a bad thing to do, just try to make sure it's both ways where possible so non-dog players don't get screwed either. Can an AI use a Research Shell?

**Comment by Repede** [comment]
AIs can't use a Research Shell, so they can't make more of themselves. neither research or dogborg science shells

**Comment by Holdelta** [comment]
So, just to add perspective here, I've posted visual comparisons of the tools between normal Sciborgs and Research Hound
https://imgur.com/a/jkVH0Wd

Research Hound still has a few less tools, but considering they have fun dog things to use, I didn't add all the things to it.  Pupdozer module seems to be fine to add those few things in though is what I'm sort of feeling right now.

**Pull request merged**
