### PR TITLE
New Cyborg Skin

### PR DESCRIPTION
**Pull request by SarmentiCampbell**
Requested by Lywarra/Serena, Basically, Add a new skin to some modules, Credit to Bananrang who gave permission.

Also, Why do robot-yw don't work?

### CODE REVIEW

**Comment by izac112** [comment]
because the way the code works it selects the sprites from the other file, still recommend leaving a copy of the sprite in robots_yw.dmi so when we do voreupdate and it overwrites we got the sprite to import again

**Comment by KillianKirilenko** [comment]
Look at how it's done in `..\code\modules\mob\living\silicon\robot\robot_vr.dm` and `..\code\modules\mob\living\silicon\robot\robot_modules\station_vr.dm`. The 'downstream' variants are added on seperately.

**Comment by SarmentiCampbell** [comment]
I.. don't know, Honestly I saw that the servitor was added that way aswell.

**Comment by Liu-Junior** [comment]
Oh please merge this * - * Such a beautiful model.

**Pull request merged**
