### PR TITLE
Fluff: CentCom Officer Cloak and Uniform (Teshari) for Strix Hades

### PR DESCRIPTION
**Pull request by Repede**
Adds a fluff item: Teshari CentCom Cloak and Uniform
Added to Strix's loadout.

Feel free to talk about whether it's a good idea or not to have the Host play a CC Officer even outside of events in this PR, but I've had support from some players and staff, some others may be against it.

Also makes Teshari not lonely around AI holograms.

### CODE REVIEW

**Comment by Hawk-v3** [comment]
The only prerequisite is you keep playing Strix as someone who gives a shit and wants things to be peaceful, not someone with ultimate power. :D

**Comment by sleepyretard** [comment]
ur not retord is ok :))))))))

**Comment by RadiantFlash7** [comment]
I personally dislike CC officers in general, being on station.
However, if anyones able to play it responsibly, you can. So, go for it.

**Comment by ValiantEsp** [comment]
Do it. If anyone can do it right, it's you.

**Comment by cebutris** [comment]
I wasn't going to add my opinions on this, but since other people are doing it...

CentComm officers should not be a regular thing on the station outside of events (this is coming from someone who for a very long time had a character who was a centcomm officer on another server). The issue I have with it is hard to explain. It kind of... makes a more clear divide between the admins and the regular players. Ideally, there should be as little divide as possible. I shouldn't look at another character and think "That character is canonically better than any character I can make and there's nothing I can do about it". On a roleplaying setting such as this, I personally believe everyone should be on equal grounds when it comes to character creation.

That said, during events it's different, and I have nothing against giving the snowflake bird raptors centcomm clothing that fits them

**Comment by Repede** [comment]
Do you think that the server you played on suffered because you played a CCO on it for a very long time? I'd assume it was still populated and people still had a good time, or was there players who hated staff just because they snowflaked it up?
I also don't believe that rank means canonically better, there's plenty of head of personnel players that are just bad. There are people who play a Miner character that's still more interesting than anyone else on station, etc.
A reason I'd also like to play CCO more is that it will also give a much direct bridge to get CC involved with a matter without having to fax spam, when someone does a bad or whatever and they have no direct supervisor, it's easier to notice said bad if the authority person is right there to witness it and make a report without admins currently playing having to actually hide their characters or cryo them just to get IC involvement that isn't just "nice fax, we'll investigate". It's a bit of a way of saying you can get IC admin intervention simply by reporting it to the CCO.
And as CCO, other than routine inspections and such I really don't plan to rule over the other heads or anything, just a fancy IAA.
And finally, if people really complain and don't like it we can dial it back or just stop with it. I hope I'll be nice enough that it would never get to that but there's always that fallback.

**Comment by Hawk-v3** [comment]
Strix gets fired from Centcomm: Ate all the icecream. Not from the station, the planet.

**Pull request merged**
