### PR TITLE
[JOB/ACCESS] Security Pilot

### LINKED ISSUE #567: Missing Items from Loadout: Pilot Jumpsuit and Helmet
Originally there were two items in the loadout screen. 

Under Uniform and Casual Dress, there was
 "/obj/item/clothing/under/rank/pilot2" 

With the description "A dark blue NanoTrasen flight suit. Warm and practical, seveal patches are scattered across it."

Under Hats and Headwear there was
"/obj/item/clothing/head/pilot/alt" 

With the description "Standard pilot gear. Protects the head from impacts. This one has a retractable visor"

Both of these items are in the code still, and they share the same name with their equivalents. I will provide a photo for comparison.

https://puu.sh/F9fAh/d29bf5c526.jpg

As far as I am aware, there is no way to obtain the set on the left (the one i'm talking about) without an admin spawning them in. (Thank you Legion for the assistance).
The set on the right is the set that pilots spawn with.

I should also mention, the alternate pilot jumpsuit also spawns with a unique pilot's harness. 

I propose that they spawn inside the pilot's lockers, or they are returned to their place in the loadout screen.

### LINKED ISSUE #657: Security pilot Officer Job
#### Brief overview of the feature
Security pilot officer job.
Flies Security interceptor shuttle, (heads to a few locations, formerly labor camp shuttle)
Pilots Security Rover. Mecha like 4 wheel vehicle that moves quickly in the snow, intended for snow patrols.

#### What you want to happen
Add New job for security stuff.
 
#### Anything else you may wish to add:
- (Pilots area within security, to be added in a blank tiled maint spot.)

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Adds "Security Pilot" job as requested to fix #657 with their own access level, uniform, outfit datum, and so on.

Also restores the pilot suits and webbing requested to fix #567.

### CODE REVIEW

**Comment by izac112** [comment]
👌 though it probably should not be merged until we get the shuttle fix and the sec shuttle actually implemented.

**Comment by izac112** [comment]
Also whenever you got free time could you please comment the things you missed that are not in _yw specific files.

**Comment by KillianKirilenko** [comment]
Done. Also modified how the access is added to the hos/warden so it should be less intrusive.

**Comment by izac112** [comment]
Nice.

**Comment by KillianKirilenko** [comment]
Added job-specific locker, since I realized that was overlooked.  Basically a hybrid of a sec locker and a pilot's locker. Contents;
Parachute, Survival Knife, Pilot Helmet (alt), Face Mask, Pilot's Uniform, Fingerless Gloves, Sec PDA Cart, Sec Bowman Headset, Sec Belt, SecHUD Sunglasses, Box of Flares, Spare Webbing, Liquidfood, Water, Corpsec Cap, Armpit Holster, Taser, Cell, Maglight, Radio.

**Comment by izac112** [comment]
Good work, now we just need the actual shuttle which radiant is working on iirc

**Comment by Razgriz1032** [comment]
I can't believe you're not giving it an alt title of MechWarrior

**Pull request merged**
