### PR TITLE
Gauss projectile icon fix

### PR DESCRIPTION
**Pull request by Razgriz1032**
Removed '_yw' from the path to use regular projectiles .dmi. It already has a gauss icon in it. The _yw file had 4 dir icon but projectiles only work with 1 static dir. Also just removing the gauss shot icon state from projectiles_yw.dmi since it is redundant.

### CODE REVIEW

**Comment by SplinterGP** [comment]
Coulndt just make the one in YW file 1 directional? Would make way less changes and we would be able to edit our gauss bolt if needed without having to mess with code(not a big deal but, way better imo)

**Comment by Razgriz1032** [comment]
Well I thought of my idea and your idea and brought it up on discord. Kelshark says "anything works for me personally." So you want that instead?

**Comment by SplinterGP** [comment]
if you could, yes, i'd prefer it, up to you, since what i suggested is just a single button fix and has less changes on it, up to you

**Comment by izac112** [comment]
> Coulndt just make the one in YW file 1 directional? Would make way less changes and we would be able to edit our gauss bolt if needed without having to mess with code(not a big deal but, way better imo)

Prefer it the Razgriz1032 way removes bloat and conflict risks that way. if we want to edit the bolt in the future we deal with it then

**Pull request merged**
