### PR TITLE
GeneShadekin nerf

### PR DESCRIPTION
**Pull request by Repede**
Less brute resistance, less fire resistance (human temp range), no more invincible to stuns (hopefully)

### CODE REVIEW

**Comment by Hawk-v3** [comment]
I thought this was a whitelist no-one was ever going to get~ :D

**Comment by izac112** [comment]
Nah, anyone can play GeneShadekin just not normal ones

**Comment by Shadow-Quill** [comment]
~~Shadekin whitelist when~~

**Comment by Hawk-v3** [comment]
Never whitelist. Never.

**Comment by Shadow-Quill** [comment]
uwus sadly

**Pull request merged**
