### PR TITLE
Voreupdate

### PR DESCRIPTION
**Pull request by izac112**

### CODE REVIEW

**Comment by AffectedArc07** [comment]
You crashed IconDiffBot and MapDiffBot.

Your repo has been blacklisted from both.

**Comment by izac112** [comment]
> You crashed IconDiffBot and MapDiffBot.
> 
> Your repo has been blacklisted from both.

Any clue what we did exactly that caused it?

**Comment by AffectedArc07** [comment]
image
This is a likely cause

**Comment by izac112** [comment]
> image
> This is a likely cause
Ah. 
I assume it cant handle a lot of dmi changes at once and its better if its handled in separate prs then, thanks for the heads up at least so i don't have to figure out why diff bots are not going to work it is in the future then.

**Comment by AffectedArc07** [comment]
Oh I should specify, the blacklist will be removed after this PR is done

**Comment by izac112** [comment]
Ahhh thanks. yeah sorry about that.

**Comment by AffectedArc07** [comment]
Repo unblacklisted.


For future reference, please put `[IDB IGNORE]` in your PR titles for upstream merges

**Comment by izac112** [comment]
> Repo unblacklisted.
> 
> For future reference, please put `[IDB IGNORE]` in your PR titles for upstream merges
👌

**Pull request merged**
