### PR TITLE
Biosynthetic 'Species' Project

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Long story short, a little while ago I decided to radically restructore the backstory and design of a character of mine, heavily inspired heavily by several sources. I'll let the 'species' blurb I wrote speak for itself though;

**BIOSYNTHETICS**
*"Artificially-created humanoids made of synthetic materials, biosynthetics blur the line between mortal and machine to a degree that many find unsettling (if not downright terrifying) as they can be nigh impossible to tell apart from regular flesh and blood beings unless severely injured. They are highly durable, generally fearless, and do not feel pain. Contrary to certain depictions, however, their emotional range is more or less equivalent to those of normal people, and thus they can in fact feel pity and remorse, and can usually be reasoned with."*

When making a biosynthetic, you can customize their design and pick any species base (which will also be used for suit cycling and other unique sprites), as well as a custom name, just like making a custom species.

Instead of custom traits though, biosynthetics come with their own predefined perks and drawbacks. Being made of mostly synthetic materials, they're entirely immune to viruses, infections, and the effects of many chemicals (including alcohol), and don't feel pain. They're capable of processing most healing reagents, but do so at just one fifth the rate of humans. Whilst they're more tolerant of low temperatures, they're less tolerant of high temperatures and take more burn damage (1.2x burn mod). Stun durations from shocks, flashes, and loud noises are increased by 50%. They can't be cloned if they're killed, but it **might** be possible to repair them enough to defib if they're not burned to the point of husking.

Big thanks to Holdelta for helping me test the defibrillator bypasses and convincing me that they weren't going to be completely OP, especially compared to the perks that Prometheans, Xenochimera, and Dionaea get, and the lack of access to traits like Haste. I still feel they'll be quite powerful, but I've tried to work in plenty of drawbacks alongside their generous benefits.

_tl;dr_ I made my very own super duper snowflake "species", they're kinda powerful but hopefully not too crazy.

**TODO/WISHLIST**
- [x] EMP vulnerability (less lethal than FBP, but other, stronger side-effects
- [ ] Reduce metabolism and slowdown if they don't have enough oxygen.
- [ ] Proper synthetic/artificial blood type. This could be really fiddly to set reliably, not sure.
- [x] Update the defib's jumpkit protocol to clean up tox damage, on the offchance they died to pure tox damage.
- [x] Fix assisted languages (readd vox, EAL, possibly others?)
- [ ] Rewrite the species blurb and most of this post?
- [x] Adjust EMP effects and comments (slightly more damage, chance of knockdown at tier 2/3, chance of blind at tier 4, longer blind at tier 1.

### CODE REVIEW

**Comment by SplinterGP** [comment]
to be fair, i don't think making a entire new race would be needed once you could rework on assisted organs instead

**Comment by KillianKirilenko** [comment]
Yes and no. The problem with assisted organs is that they're vulnerable to EMPs and losing them will still be fatal as far as i'm aware?

EMPs aren't fatal to biosynths (they're too advanced) but I do think it would be appropriate and fair if ion blasts and such disoriented and stunned them.

**Comment by SplinterGP** [comment]
well, since it has mechanical parts it would make no sense for EMP's not affect them, since that's the mechanic of the synth stuff, you could work around the things like FBP, but instead of being fully mechanical, making assisted arms, legs, chest that is the most important, and all that

**Comment by SplinterGP** [comment]
it would even let you be an assisted synth of any species and even custom species, letting you do it as you please mostly

**Comment by Legion2552** [comment]
I'm against this fundamentally. It just seems like this species doesn't know if it wants to be a Synthetic or an Organic, and so it just chose what it wanted from either camp and blended it into it's own mix. Toss in some negatives to make it seem 'balanced' and call it a day.

Radiation doesn't negotiate with organics. It breaks them down. It even breaks down non-organics like the Camera that took photos of the Chernobyl reactor breach. Organic material means that toxins of some kind would have an affect, certain chemicals just RUIN cells. If Bio'Synth' refers to some sort of mechanical component, rather than just being 'Synthetic' in the way that were designed from top to bottom, means that EMPs would totally effect them. If it's not that, you don't get Robotic Advantages (like not caring about blood, oxygen and toxins) without the drawbacks of being BIG OOF'd by EMPs. Ignoring Pain is a terrible mechanic, as people already don't actually care about pain. Tasers hurt like a bitch, you don't want that. Yet people will routinely keep resisting Security and make them use 10+ Tasers blasts so that they are MADE to go down mechanically. Having Role Play negatives aren't negatives at all.

I think more than a 'balance' check this needs a thematic and identity check. It's more like they don't know what they want to be, and therefore they just became a hot pot of things that sounds good. With some slight negatives mixed in.

It's a hard no from me in their current state.

**Comment by KillianKirilenko** [comment]
I'm definitely not against reintroducing toxin damage in some form (I was a bit heavyhanded in my initial passes), and I can probably remove the rad modifier or even increase it to a negative one so that direct burn damage from high rad exposure is a much more significant threat to them.

As for tasers; they're still *very, very* vulnerable to those even without the pain resist.

**Comment by SplinterGP** [comment]
you kinda gotta Decide what it is, for real, are they humans that have synthetic parts to aid them, synthetics with few biological parts or what.

**Comment by SplinterGP** [comment]
if they are organics with synthetic parts to aid or improve them, you could add Augments on robotics and have them save between rounds, having augmented arms that take a bit more damage and that type stuff(with tradeoff of being synthetic)

**Comment by KillianKirilenko** [comment]
Part of the problem with the background is that I've tried to leave a lot of the 'specifics' open to people specifying however they wish for their own character creation. They're not necessarily all prototypes from Vey-Med, or saboteurs created by rogue super-intelligent positronics, or who knows what else.

Let's start with basics for a moment though. Imagine a bone, except it's made out of porous metal, with a ceramic outer layer. Now imagine it's connected by elastic artificial materials, and that muscle power is provided by synthetic fibres that contract with exposed to electrical impulse. Fluid-carrying vessels provide energy and the materials needed to maintain these components at the cellular levels. It's painstakingly accurate mimicry of organic design, all that differs is the materials used.

Simply put, I'm very skeptical of any "that can't work" arguments considering we have slimepeople, living viral messes, and tree-people-gestalts. But again, I'm absolutely in favor of adding stunning and similar effects from EMPs, I'm just not sure *how* to make that happen codewise.

**Comment by SplinterGP** [comment]
well, then, they are people but instead of made out of flesh they're made of metal ?

**Comment by RadiantFlash7** [comment]
I think the fundamental issue is trying to leave background open on a new species that will be featured like other species with set backgrounds.
It’s one thing to have your own backstory for a character, but certain specifics involving the species *must* be nailed down. 

If some people want something different, thats when they break out the custom race creator.
Otherwise, my opinion runs parallel with legions.

**Comment by KillianKirilenko** [comment]
Not *just* metal. Artificial/synthetic includes a much wider array of materials! To the touch, a biosynth's skin/fur feels like skin/fur, it's just not made of the same stuff as ours is. It's very very hard to tell they're not 'meat' without straight up cutting them open, much like how Vey-Med and DSI prosthetics have the 'lifelike' flag that doesn't reveal their nature on examine.

Internal organs are where things get fuzzier. Biosynthetics still need to eat and drink, using a 'chemical furnace' to break down what they ingest in order to pull materials and energy out of it, much like a biological digestive system. Their 'blood' still needs to circulate for them to function properly, so if their heart (or all of their blood) is removed or destroyed they're basically comatose.

**Comment by Legion2552** [comment]
Which is my point in a nutshell. All that painstaking background is great, but you can do that with custom species traits. A whole new species that takes positives from both Organic and Synthetic and has a pair of Custom Species negative traits to compensate just isn't a good idea. 

On top of that, slow metabolism is a good thing. Chems last longer. Sure they work slower, but at the same time they don't take Toxin damage. Sure you mentioned you could do Toxin damage again, but that's what Overdosing is. Toxin damage. So just shoot yourself up with 300 Bicard. Boom you're basically super resistant to brute damage for a way longer time now. Toss in 200 Hyperzine, some hyronalin, a bunch of other chems too. No overdose toxins right? Go nuts. 

Sure, it makes sense to give them more HP. Metals are stronger than bones, but do they really need that mechanical advantage? Biosynths don't really give a shit about radiation, but too much will still hurt. Well why? Normal people and synths care about Rads. Why don't these guys? 

It just seems like Organics with extra steps, and those extra steps are reasons they should be stronger based on this character, and not reasons that would make sense in the context of what's already available, and what's already established. Like Cyborgs, FPBs, and just normal flesh and blood people.

**Comment by SplinterGP** [comment]
well, so their things are basically that they are synthetics that mimics organics, it ain't hard to be fair, you could pretty much make a way to be a synth and instead of using the default energy ways, use other ways of making power, as in, instead of making a FBP by switching to a synthetic chest you could make an assisted/biosynth chest, that instead of recharging by rechargers they need food and drinks, and they still use blood but a special one and they don't breath like synths.

**Comment by KillianKirilenko** [comment]
I'm not even going to touch on the OD thing right now because I could absolutely rant for a paragraph or two about dionaea and how chems are fucky in general, and that's not a good look for anyone.

For the moment I'm focusing on the radiation point since I'll concede that, yes, they should probably give more of a fuck and attempting to make them do so. Running into some interesting hiccups due to the NO_POISON flag I think.

**Comment by Legion2552** [comment]
Yeah but the OD thing is as well on top of everything else. It's not a simple "I'll just make Rads affect them and call it a day." change. It's a pile of things. From where they would fit on the Organic/Machine balance, to what all happens to distinct traits to other mechanical differences. You kinda summed it up well in your TL:DR. It is a snowflake personal race based on a character that is at its core "Basically a FBP but better." Sadly, too crazy to pass inspection by us at this time.

Dwaggy made a comment in the Adminchat I can understand, but I don't agree with. 

"Like i dont wanna outright shut him down on this cause it looks like they've done a lot of work on it..but.. they're..kinda already pushing in to places that exist already?"

Yes, you did do the work on this. Yes, I don't want to discourage you from doing further things. Sadly, no it doesn't really fit with what we have in mind for adding new species. You're welcome to refine it and try again, but like RadiantFlash said, there's a serious problem with Species being 'just do your own thing' when we have Custom Races for that. The Set Species are supposed to be designed a certain way. Sure you can make a human that's different, or get a Custom Species that looks like a human but with slightly different traits.

**Comment by KillianKirilenko** [comment]
I definitely don't want them to be just 'FBPs but better', which is why I've tried to attach other issues beyond the stun weaknesses (which are justified in my own notes, but I've not wanted to go throwing out giant walls of text).

I'm open to ideas and suggestions of all stripes, whether that's stuff like immunity to beneficial chemicals as well, or removal of most of their immunities to harmful effects, but I can only work with what I'm given or what might be considered acceptable.

There is one big, key element from my notes that I'd like to add, bigger than synthetic blood or stuns from EMP: biosynths still benefit from the presence of oxygen, so a thematic flaw that I'd very much like to integrate would be reducing (or even completely halting) their ability to metabolise substances and applying a slowdown modifier if they don't have enough oxygen available.

**Comment by KillianKirilenko** [comment]
Managed to hack in EMP vulnerability that deals a fairly nasty amount of toxin damage and disorientation (highest-tier EMP will actually blind+trip you briefly), restored toxins entirely (representing waste material buildup), reduced max health to standard values, and removed incoming rads modifier (as it is mostly used to determine tox damage from radiation poisoning).

**Comment by Repede** [comment]
@Legion2552 @izac112 @RadiantFlash7 Anything you guys want to add?

**Comment by izac112** [comment]
Personally for me the **main problem** is not just like balance in itself (that can be fixed) its more like what is the point of making this their own thing what makes them special BESIDES just different stats and immunitys that are just strong. like what is the gimmick.

Just seems like a stronger human / fpb

like greys have their gimmick with the whole tele, they are not stronger than humans combat wise in any way they are actually weaker plus once its implemented they wont be able to speak common without an implant and that implant will be effected by emps iirc.

The Bio synths got a lot better with the commits you made though.

Problem is just at this moment they are just humans that are immune to viruses,don't feel pain, don’t breathe, take more taser damage, for some reason can speak every language with ease even though their voice box is not mechanical, has a slow metab, cant die of blood loss and don’t like it when its too hot.
That is just something you could do with a custom species in game (at least the changes i find reasonable) before the commits they were all that plus they did not take toxins and barley took rads.

TLDR: They need a gimmick something that gives them a reason to exist instead of just being a custom species with their own selection, lore needs to be a bit less open ended though thats not a requirement 

"that many find unsettling (if not downright terrifying)" piece of the lore needs to go because its just sounds edgy and why are they fearless do they not care if they live or die?


Also sorry if i sound like a dick but i rather not beat around the bush.

**Comment by KillianKirilenko** [comment]
> Also sorry if i sound like a dick but i rather not beat around the bush.

No offense taken! I appreciate the honesty and value clear communication as it's something that's sorely lacking in many circles. As long as there is no malicious intent intended, it's all good.

The main issue here is that the best way to describe them is, yes, "organics/FPBs but better". The description provided (particularly the unsettling/terrifying part) is meant to play into the 'synthetic horror' tropes, similar to the replicants in Blade Runner, the Hollow Children from Binary Domain, or Ash and Bishop in the Alien(s) franchise. Not everyone finds them scary, and indeed I'm sure many here both in and out of character are of fairly open mindsets, but there are absolutely bioconservative and religious type factions and individuals out there who would find the notions of them to be nothing short of blasphemy.

Mechanically, the breathing part has actually been rather difficult to work with and still not something I'm settled on - but I'm at a loss for how I can nail down the big feature I've mentioned. Even though I've tried making them resistant to low pressures, their lungs are still taking depressurization damage which causes them to gasp and cough up blood.

As for the fearlessness, I can probably just strip out that entire sentence from the blurb at this point, or else I should probably just rewrite it entirely at this point.

Regardless of suggestions (which I'm still open to) I might close this PR for now whilst I continue to tinker with things behind the scenes, and then squash all the commits down. Before I did that, the project was up to something like 14 or 15 commits from revisions and testing.

**Comment by SplinterGP** [comment]
The lung depressurization is a var coldbreath_level or something, look at human or carbon.dm

**Comment by Hawk-v3** [comment]
I'm marking this for my own reminder, don't take this as me denying it.

**Comment by KillianKirilenko** [comment]
Closing for now. Probably going to move changes to a new branch and keep tinkering for a while, lots more tests to run, but I was busy with #638 lately.

On the plus side I think I now have a better idea for how to handle lore/history for them in a way that doesn't close off too many options.

**Pull request closed without merging**
