### PR TITLE
Mapfixes Pass III: Camera Networks

### PR DESCRIPTION
**Pull request by KillianKirilenko**
What the title says.

- [x] Telecomms
- [x] Cargo
- [x] Civilian
- [x] Engineering
- [x] Substations (NEW)
- [x] Exploration
- [x] Medical
- [x] Outside
- [x] Research
- [x] Research Outpost
- [x] Prison
- [x] Security

### CODE REVIEW

**Comment by KillianKirilenko** [comment]
All the worst camera network issues should now be fixed, despite DreamMaker's best efforts to fuck things up (I think I understand why the current networks were in such a state, incidentally: don't have multiple dmms open at once!). The Outside network has been populated with a selection of cameras around key locations in particular.

Substations are now on their own Substations network, and missing hazard stripes + lights have been added to substations where they were missing.

Field Medic access to Exploration should be fixed for real now.

Motion cameras have been installed at key locations.

There are likely still blind spots, and some minor inconsistencies in naming (some areas use ship-style directions, others use cardinal/compass directions) but otherwise the bulk of the issues reported in #751 thusfar have been tackled.

**Comment by SplinterGP** [comment]
virology freezer doors don't let virologist enter it, but seems its access is right, probably virologist has no virologist access ?

**Comment by KillianKirilenko** [comment]
Alt titles don't edit your access levels at all, so that's no surprise.

My assumption is that the frozen samples are kept locked up to prevent griefing. It's one thing for them to abuse chemlab to make chloral and try to kill a couple people, it's another thing entirely to homebrew a highly deadly virus and set it loose on the crew.

Not touching this one without full admin/staff commentary for that reason.

**Comment by Dwaggy** [comment]
My thoughts on the virology stuff is to, yeah, let the access to the frozen samples area be initially CMO locked. that way they can decide if they trust whoever is asking to fuck around in virology or not.
Granted, this does mean if theres no CD/CMO on, or they decide they dont like you..
Your..kinda..shit out of luck for that whole job and you may as well leave..which..shouldnt be a thing.
But..the alternative is giving the keys to kill everyone on station in minutes if they dont know what their doing. At least this way, a cmo/cd can decide, or preferably teach them if they dont entirely know..

**Comment by izac112** [comment]
Its most likely a mapping error i have never seen anyone attempt to virus grief a single time since box station.

**Comment by izac112** [comment]
Though can just ask directly @RadiantFlash7 is the frozen samples meant to be inaccessible to med docs?

**Comment by SplinterGP** [comment]
yeah the doors to door freezer has virology access(opened them myself) but they don't open(dind't see if the virologist had viro access on guest pass) it could be a mapping error seeing its a vault door ant they have some variants which need red alert and such stuff, gotta give radiant a poke about it.

**Comment by SplinterGP** [comment]
also it takes too much effort to make a virus that is able to grief around, don't think a griefer would do it, it would be easier to spread a lethal virus by accident than griefing in my opinion

**Pull request merged**
