### PR TITLE
Recoil knockdown code for micros

### PR DESCRIPTION
**Pull request by Razgriz1032**
From old chomp: https://github.com/CHOMPstation/CHOMPstation/pull/619

This will add "recoil" to smol people. Weakens them and has a very tiny damage penalty.

Original message:
Code to make anyone under 50% take recoil damage (5 brute - your size * 2; so at 50% thats 5-1)
Also makes tinies fall down from firing guns.

First step in giving being a micro combat downsides for being so hard to hit.

### CODE REVIEW

**Comment by Razgriz1032** [comment]
Actually, before merging, would you like for the size gun to have no recoil for micros?

**Comment by izac112** [comment]
Well first have to ask @Repede If he be fine with it but if it's getting added any laser weaponry should probably not be effected by it as lasers have no recoil.

Short answer yes

**Comment by Repede** [comment]
Could maybe turn that block into a proc so we can override it between weapons? Could make lasers less 'oof' separately, because while it makes sense to get projectile recoil that knocks the tiny retards back. Lasers should probably not have more of a kick IMO?

**Comment by izac112** [comment]
Agree with that

**Comment by Razgriz1032** [comment]
I have an example of code from @Sharkmare that adds a variable that you can tweak for guns, but also works as a multiplier for damage and weaken. I could also work in some code to exclude damage from energy-specific weapons.

It's in this commit, currently affecting both weaken and damage.
https://github.com/CHOMPStation2/CHOMPStation2/pull/144/commits/be294c3e9274fe93b1f5653c3a5b007f6b17e2a9

**Comment by Razgriz1032** [comment]
There you go. Check that out. Also comes with distinguishing red text so that the person using it doesn't just go "huh? Wha happe?"
image

So from here you could make a new file, title it gun_recoil.dm or something, and then list out every single gun and then just have one variable under each pathname, "var/recoil_mode = int"

**Comment by izac112** [comment]
This good to go then?

**Pull request merged**
