### PR TITLE
Prometheans clean everything.

### PR DESCRIPTION
**Pull request by fludd12**
Prometheans now clean everything they're wearing and holding, as well as themselves - along with, of course, the tile below, if they lack shoes.

This is mostly because I got insufferably tired with having my feet get soaked in blood while cleaning blood, which made no sense.

### CODE REVIEW

**Comment by Repede** [comment]
Can you make sure to wrap the beginning and end of those changes with //Yawn Edits Start and //Yawn Edits End?

**Comment by Repede** [comment]
Also why not just have it clean your feet / body only?

**Comment by fludd12** [comment]
This is also PR'd on Polaris, so theoretically it wont be a Yawn Edit for much. Also, I felt that cleaning everything made sense with their filter-feeding style.

**Comment by Repede** [comment]
Maybe once we see Polaris' decision we'll see wether to merge or not, because if they merge then we shouldn't since the change will trickle to us

**Comment by fludd12** [comment]
I'm used to having to put out releases on both upstream and downstream stuff since parity updates tend to be pretty few and far between on the servers I frequent. Either way, with how git works, merging both wouldn't hurt anything.

**Comment by izac112** [comment]
https://github.com/PolarisSS13/Polaris/pull/6468#event-2689731422
Polaris merged it on their end so should be good to go here

**Comment by fludd12** [comment]
❤️

**Pull request merged**
