### PR TITLE
Releaseupdate

### PR DESCRIPTION
**Pull request by Repede**

### CODE REVIEW

**Comment by TheFurryFeline** [comment]
Fair warning, the new chat system from Virgo has bugs currently being worked out. Most notably chat logging issues

**Comment by SplinterGP** [comment]
yep we know that, we testmerged, and we also had alot of lag, as in, the chat itself having big ping

**Comment by SplinterGP** [comment]
other than that i don't mind chat log not saving correctly, i think we aren't able to have that with goonchat as the dude who made it said

**Comment by TheFurryFeline** [comment]
Thing is, Arohka/Aronai has been working on fixing the logging issues as well as the other stuff.

**Comment by SplinterGP** [comment]
yeah we spoke with them, general issue i mostly had was the lag, other than that i don't log any shit so am good

**Pull request merged**
