### PR TITLE
Adds GeneralPantsu requested emotes, *ack, *ough, and *hooh

### PR DESCRIPTION
**Pull request by SplinterGP**

### CODE REVIEW

**Comment by Mocha-Not-Latte** [comment]
Cursed

**Comment by izac112** [comment]
This seems a bit too meme considering we even removed the HOOH from the gnome plants

**Comment by SplinterGP** [comment]
They dont even show on emote list, so i think its fine and im sure people wont spam it much, the ack is neat tho

**Comment by SplinterGP** [comment]
And i see why they were removed from gnomes, they were being too spammed on station even after it got removed

**Pull request merged**
