### PR TITLE
new tesh radsuit

### PR DESCRIPTION
**Pull request by KBraid**
the bubblehead of the tesh rad hood teels so out of place compared to the regular rad hood so i made a new one that better matches it. the whole tesh rad uniform is also rather odd and inconsistant so i edit it as well.

### CODE REVIEW

**Comment by KBraid** [comment]
image

**Comment by izac112** [comment]
It gud to go now?

**Comment by KBraid** [comment]
should be, i'll give it a quick test first

**Comment by KBraid** [comment]
it's rtm

**Comment by KillianKirilenko** [comment]
For everyone's sake, if you're editing upstream dmis, either put it in a seperate file and override or port it upstream. DMI conflicts are a *huge pain in the ass* to fix.

**Comment by izac112** [comment]
^^

**Comment by KBraid** [comment]
i'll do that quickly

**Comment by izac112** [comment]
Stale

**Pull request closed without merging**
