### PR TITLE
Traffic & Lore Update, Vol. 1

### LINKED ISSUE #629: The Traveler's Guide to Human Space: Borealis Edition still refers to Virgo Erigone
#### Brief description of the issue
While the title of the book has been changed many areas in the book still refer to Virgo Erigone including, the home page, about section, and everything in important locations.

Also, the political section is blank and should just be deleted.
#### What you expected to happen
The book to refer to Borealis

#### What actually happened
The book refers to virgo

#### Steps to reproduce
- Get the book
- Open the book

#### Code Revision
Server revision:  - 2020-03-02
420b825864fd6ff50ada40a412b2f59d8323e4aa

### PR DESCRIPTION
**Pull request by KillianKirilenko**
A fairly hefty update of the traffic system with nine new factions, a new event, new destinations, and proofreading/error-correction on several existing descriptions.

Fixes #629 

UNDER THE HOOD:
- More comments! Better internal categorization!
- "Complex Task" logic. Generate an additional layer of assignment, allowing the designations to be used for subfactions.
- Tweaked some event weights.
- Automated Tram/Shuttle name can now be defined map-side. Defaults to "NAS *Faraday*" if no name is provided.
- A bunch more ship names for the existing factions, including several more for the 'generic'/default pool.

LOREBOOK:
- Updated with Borealis system data!
- Most of the planets and locations have no data though.
- Now shows factions from the Other category (SDF, Independents, Pirates, Vox, _etc._)

EVENTS:
- Split several responses from Docking Request Denied into Docking Request Delayed, which works like Undocking Request Delayed.
- Minor tweaks to existing event text.

DESTINATIONS:
- Dozens of real, named exoplanets! No idea how habitable they are. Could all be gas giants. We won't know for a while!
- Updated existing destinations! Based on Polaris lore still, mostly.

NEW FACTIONS:
- [TSC] Oculum Broadcasting: they tell you what you want to hear, before you know you want to hear it.
- [TSC] Centauri Provisions: responsible for almost everything edible and drinkable. Mmm, Bread Tubes™.
- [TSC] Einstein Engines: 'third wheel' is generous, these guys lag behind the power game like no other.
- [TSC] Wulf Aeronautics: they build it, you fly it. Shipwrights specializing in freighters and transports.
- [TSC] Gilthari Exports: where there's money, there's people who want to spend it on dumb expensive bullshit.
- [TSC] Coyote Salvage Corp.: unionized shipbreakers and legal salvage operators, and the nemesis of vox everywhere.
- [GOV] Almach Association: a progressive, transhumanist group from the fringes of USG territory.
- [MIL] Almach Revolutionary Vanguard: the Association's ragtag irregular military force, their answer to the USDF. Uses the new complex tasks system.
- [OTHER] Ue-Katish Pirates: skrellian miscreants, because not all pirates are human or vox!

### CODE REVIEW

**Comment by SplinterGP** [comment]
Can you put greys in the book?

**Comment by KillianKirilenko** [comment]
Sure. Point me at the relevant text entry on a wiki or post it here and I'll add it in.

**Comment by SplinterGP** [comment]
I think the cataloguer has a good one, let me get it

**Comment by SplinterGP** [comment]
datum/category_item/catalogue/fauna/grey
	name = "Sapients - Grey"
	desc = "The Grey are a species of genderless grey skinned aliens.\
	Greys lack a language of their own, communicating with their kin telepathically. Though their formal names used through\
	telepathic communication lack a written counterpart, many Grey adopt written names for the purposes of interacting with\
	other species or record keeping. Due to their lack of a spoken language, however, these names do not normally follow a\
	scheme or pattern, varying greatly from individual to individual.\
	<br><br>\
	It's believed that Greys have originated\
	outside of the milky way, on another galaxy. From observing the anatomy of various Greys, xenobiologists have come to the\
	conclusion that Greys likely did not go through a natural process of evolution, but were instead engineered,\
	likely by another master species, in a similar fashion to the Vox Primalis commonly found aboard Nanotrasen stations.\
	The true origin of the species appears to be unknown to even the Greys themselves, who are believed to have arrived from\
	a distant galaxy cluster after a long period of extended cryosleep. Due to these peculiar circumstances many\
	Grey have elected that Mauna-b, which has a high population of Greys, act as a stand in for their home planet.\
	<br><br>\
	Grey physiology is unique in several ways. While they have similar respiratory and vascular systems to humans - breathing\
	oxygen and expelling carbon dioxide - it is important to note that instead of producing hemoglobin to transport oxygen,\
	Greys produce hemerythrin, which causes their blood to take on a violet colour when oxygenated. Hemerythrin is\
	unfortunately much less effective at distributing oxygen throughout the bloodstream, which lead to issues of\
	hypoxemia in the Grey population aboard non-Grey facilities.Furthermore, due to high salt concentrations,\
	the cells in a Grey's body are known rapidly undergo cytolysis when brought into contact with water - a reaction\
	which can prove immediately fatal.\
	Grey eyes are almost triple the size of those of most other species, and their sclera, iris, and pupil are completely\
	indistinct from one another. The large size of Grey eyes is believed to be an adaptation to shield the ocular nerve\
	against ultraviolet radiation with their unusually monotone complexion providing a similar degree of protection.\
	This has lead scholars to believe that in addition to likely being low gravity, the original homeworld of the Greys\
	likely had a poor magnetosphere or was unusually close to its star.\
	the Grey population appears to be wholly sustained via a form of advanced cloning; due to this abnormality Grey\
	family structure typically consists of a single parent. Greys are often cited as being highly-reserved and independent,\
	and appear to be able to go with little to no social interaction for extended periods of time without suffering any\
	ill-effects. Though Greys are not sexually dimorphic, they often adopt male or female accoutrements for the sake of\
	clarifying communications with other species, or even make gene-mods in some cases."
	value = CATALOGUER_REWARD_TRIVIAL

**Comment by SplinterGP** [comment]
There's also grey wiki, take just any important part you find enough https://www.yawn.ocry.com/index.php?title=Grey

**Pull request merged**
