### PR TITLE
Additional Resting Sprites for J9

### PR DESCRIPTION
**Pull request by Nethaufer**
Noticed that the J9 module sprite was missing all of the extra resting, sitting, and belly up sprites so I added them in by color swapping the existing sprites of the other vale models to match the J9 model.

### CODE REVIEW

**Comment by Shadow-Quill** [comment]
I'm sure upstream wouldn't mind having this as well

**Comment by Nethaufer** [comment]
I was under the impression it was YW specific because of the filename

**Comment by Shadow-Quill** [comment]
Ah, I see. ¯\_(ツ)_/¯

**Comment by Repede** [comment]
Can you try logging in on https://travis-ci.com/ and signing with github, it's marking your account as 'abuse' and will not run checks on your PRs until they're contacted about it.

**Comment by Nethaufer** [comment]
Signed in on it, linked my account, told me to contact support. Shot off an email regarding it. Will respond back when I, hopefully, get it sorted.

**Comment by Nethaufer** [comment]
It's been cleared up, should be good to go.

**Comment by Repede** [comment]
You'll need to close and reopen the PR for Travis to trigger if you don't mind doing that plez, thanks.

**Comment by Nethaufer** [comment]
Done.

**Comment by Repede** [comment]
Yup Travis is running :D

**Pull request merged**
