### PR TITLE
[READY] Fixes everyone having the resize verb

### PR DESCRIPTION
**Pull request by Shadow-Quill**
Tested and working

### CODE REVIEW

**Comment by Hawk-v3** [comment]
Y'see that comment right there? The one you opened with? Yeah, so-

**Comment by Shadow-Quill** [comment]
Acceptable, didn't even want it merged yet.
I test my stuff before I ask for merge

**Comment by Hawk-v3** [comment]
Ah, typically a PR is saying "This is ready to be pulled in" hence Pull Request.

**Comment by Shadow-Quill** [comment]
It was a quick webedit, as I wasn't at my computer at the time. Prolly should've added a dnm though, my bad.

**Comment by Hawk-v3** [comment]
Fair enough! Didn't know you could do that.

**Pull request merged**
