### PR TITLE
Can now alt-click APCs/Air alarms to (un)lock them

### PR DESCRIPTION
**Pull request by Shadow-Quill**
Alt-Click an air alarm/APC to un(lock) them, if you have Proper Access:tm:.

Tested and works.

### CODE REVIEW

**Comment by izac112** [comment]
Neat, might want to also push this to polaris or vore if they like it. though that is up to you.

**Comment by Shadow-Quill** [comment]
will do!

**Comment by Shadow-Quill** [comment]
but also keeping it here because I want it naow

**Comment by izac112** [comment]
Well yeah of course 👍

**Pull request merged**
