### PR TITLE
Fixes the basic collars to work on teshari 

### PR DESCRIPTION
**Pull request by Repede**
using the poncho abuse system, totally ready to break them fluff collars.

### CODE REVIEW

**Comment by SplinterGP** [comment]
Collars are like ponchos that you can equip or attach?

**Comment by Repede** [comment]
Yes they are, can be attached to jumpsuit or worn on suit slot

**Comment by SplinterGP** [comment]
Btw i think there was a sprite sheets for icon override or something like that, but anyway, on accessory _yw has the fix for the things that dont use collars_vr.dmi

**Comment by SplinterGP** [comment]
Also instead of a else, put a return and do the dropped() like the poncho fix

**Comment by SplinterGP** [comment]
It will make until you drop or a teshari wears it wont bug

**Comment by Repede** [comment]
`//ywedit start. replaces a else by a return, so it don't changes  if not teshari to ties.dmi
/obj/item/clothing/accessory/collar/equipped() //Solution for race-specific sprites for an accessory which is also a suit. Suit icons break if you don't use icon override which then also overrides race-specific sprites.
	..()
	var/mob/living/carbon/human/H = loc
	if(istype(H) && H.wear_suit == src)
		if(H.species.name == SPECIES_TESHARI)
			icon_override = 'icons/obj/clothing/collars_seromi_yw.dmi'
		update_clothing_icon()

/obj/item/clothing/accessory/collar/dropped()
	icon_override = 'icons/obj/clothing/collars_vr.dmi'
//ywedit end`

Something like this then?

**Comment by SplinterGP** [comment]
Yeah that works better.

**Comment by SplinterGP** [comment]
If you can, before one of the fluff collars break, put a dropped with the fluff items path for the fluff colars somewhere, like accessory_yw

**Comment by Repede** [comment]
Going to try something that shouldn't require to override on drop for every item

**Comment by SplinterGP** [comment]
Actually dont seems like these will affect most fluffs since they dont use the collar pathing,  but hope you manage to do that thing

**Comment by Repede** [comment]
Added a `icon_previous_override` var (only to collars for now, could be done for all accessories) which is set on New, so if they ever have custom overrides it would swap back to that one properly.

**Comment by SplinterGP** [comment]
Nice, i'll see on doing on the other stuff later

**Pull request merged**
