### PR TITLE
Kelmaptweaks

### PR DESCRIPTION
**Pull request by Repede**
Adds bathroom to security and public bathroom in residentials

### CODE REVIEW

**Comment by izac112** [comment]
Probably should add a new sec break room somewhere instead of completely just wiping it.

**Comment by Repede** [comment]
Figured they could just use the briefing room as a break room as well.

**Comment by izac112** [comment]
Works for now i guess, can just add another break room on the roof or something in the future.

**Comment by Repede** [comment]
Yeah now that there's a upper level one could be snuck somewhere, I got some specific ideas about it I could look into unless someone else goes for it first.

**Comment by izac112** [comment]
👌

**Pull request merged**
