### PR TITLE
["FEATURE"] Alcohol (In)Tolerance Traits

### PR DESCRIPTION
**Pull request by KillianKirilenko**
Someone the other day mentioned that there's no traits for alcohol (in)tolerance, something that hasn't quite sat right with me for a while either. So I decided to take a quick crack at making some.

This PR adds a universal alcohol_tolerance var (def. 1) for species that acts as a multiplier to the ethanol reagent's boozy effects, along with three positive traits and two negative traits, all of which focus on alcohol tolerances. For 1, 2, or 3 points, you can reduce alcohol effects by 25%, 50%, or 75% respectively, or you can double or triple the effects of alcohol to gain 1 or 2 points.

I haven't converted any of the species over to use the tolerance var in place of their defined (in)tolerances under ethanol, but that'd be easy to do if desired for consistency's sake.

Testing has been fairly light, but with the 50% modifier a custom-species critter was able to weather 60u of deathbell with nothing more than a lot of dizziness and slurring. It's possible I've overlooked something here.

### CODE REVIEW

**Comment by izac112** [comment]
Personally think it looks good as is, no need to convert the other species to use the tolerance var unless you plan on porting this upstream.

Nice work though, wanted something like this for a while.

**Comment by KillianKirilenko** [comment]
Not sure what's up with Travis here. It looks like all the checks are clear but it hasn't updated the main progress thing.

**Comment by Repede** [comment]
Looks good to me too 👌

**Comment by Legion2552** [comment]
Having an beer intolerance give you one or two points is too easy to power game. You either get booze in you by being fed it (yeah okay killer plan guy) or you drink it yourself. It giving you points you can get Haste with instead is a big issue. I'd make them all neutral traits, since they don't really have an effect outside an RP environment. It's different to "I'll go down in two punches/tasershots/lasers less" with the other negative traits. It's too small to affect the balance like this will.

**Comment by KillianKirilenko** [comment]
That was definitely one of my concerns as well, and it's why the point values aren't any higher.

*That said* I'd be lightly against making them all free or completely neutral. Some alcoholic drinks do have mildly beneficial effects, particularly vodka being able to clean up radiation.

I'm inclined to go with @Repede 's approach unless anyone has any stronger arguments on the matter.

**Pull request merged**
