### PR TITLE
Adds in 5 more Partical Smasher Recipe

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Lead to Diamond, with carbon. Needs a lot of heat and power for this. Likely better to just wait for more diamonds but gives a use for lead!

mhydrogen into verbium, needs a low and fickly power and rather colder temps but is doable within a reasonable shift.

marble into mhydrogen, takes hydrogen and same fickle settings to themhydrogen into verbium. Gives marble a use in sci

iron into plasteel, needs phoron and stander power for things, easy to make/fine so shouldnt be hard to make

plasteel into durasteel, needs tons of power and colder temps do to being durasteel.

These add more options then just making tons of morphium and crying at miners to get verbium

### CODE REVIEW

**Comment by GeneralPantsu** [comment]
I'm entirely against that change. Sure, it adds onto things science can do, but at the same time takes it from mining. Might as well get rid of mining entirely if this passes since you can literally just "not be assed" to do things and still end up satisfying Science.

**Comment by RadiantFlash7** [comment]
I’m in the same boat as pantsu here. While I’m all for new types of material for the PA to make, I don’t feel like simply adding the ability to bypass mining is a good fit.

**Comment by Trilbyspaceclone** [comment]
Keep in mind you need mining to get lead, marble and plasma... Also, in order to even make these you need a Particular Smasher and the PA. Also you would kinda need a lot of work to even make these leading most of the time for people to just wait for mining/getting the miners drills up and going

**Comment by GeneralPantsu** [comment]
Point still stands. Why bother grabbing diamonds and the likes then when you can just grab the most basic of ores for it. That's my issue with it. Takes a lot of depth away from things just to give another department even more of a stranglehold on things.

**Comment by Shadow-Quill** [comment]
From what I've gathered: tl;dr interdepartmental cooperation should exist, and any one department shouldn't be able to completely replace another

**Comment by Hawk-v3** [comment]
Which Science is on very shaky ground for already.

**Comment by Trilbyspaceclone** [comment]
Hmm, My points still stand, that its hard to insane to make the rarer ones, and only serves to help fluff out the list of craftables.
Im almost 100% sure to make diamond you need layers of R-walls meaning that sci should work with Engis to make a safe, heat-proof, multy use room some. Thus making it more Station helped, as cargo is already needed as well as mining. This also would need atmos's help for access and piping in theory. 
As for the chem stuff/medical toe stepping. That has no real point to this pr as those are two different issues, leading into a PR that has no real help in that regard.
All and All these are still really really hard to make imo and would need help from atmos, cargo, mining and engis to make a proper room for little gain.

**Comment by Repede** [comment]
Until your daily powergaming scientist just makes all of it on his own, the PA is laughably easy to get with cargo to turn into a particle smasher. And is sort of used for 'end game' tier items, or at least the highest tiered items. I think it's fine as is. And also, good miners will most likely get plenty of what you need already, namely diamond and verb and all, as long as they know what they're doing. And we've had tons of miners playing lately so ye. I'd rather not take work off of them and such.

**Comment by Trilbyspaceclone** [comment]
As you all wish.

**Pull request closed without merging**
